In [1]:
import pandas as pd

In [2]:
df_facts = pd.read_csv("./2016-us-election/county_facts.csv")
df_fact_description = pd.read_csv("./2016-us-election/county_facts_dictionary.csv")

In [3]:
df_facts.head()

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
0,0,United States,NaN,318857056,308758105,3.3,308745538,6.2,23.1,14.5,...,8.3,28.8,5319456312,4174286516,3917663456,12990,613795732,1046363,3531905.43,87.4
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,1.2,28.1,112858843,52252752,57344851,12364,6426342,13369,50645.33,94.4
2,1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
3,1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
4,1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0

In [4]:
df_fact_description.head()

  column_name                                        description
0   PST045214                          Population, 2014 estimate
1   PST040210          Population, 2010 (April 1) estimates base
2   PST120214  Population, percent change - April 1, 2010 to ...
3   POP010210                                   Population, 2010
4   AGE135214               Persons under 5 years, percent, 2014

In [5]:
df_results = pd.read_csv("./2016-us-election/primary_results.csv")

In [6]:
df_results[df_results["state_abbreviation"]=="AL"]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
5,Alabama,AL,Barbour,1005.0,Democrat,Hillary Clinton,2567,0.906
6,Alabama,AL,Bibb,1007.0,Democrat,Bernie Sanders,246,0.197
7,Alabama,AL,Bibb,1007.0,Democrat,Hillary Clinton,942,0.755
8,Alabama,AL,Blount,1009.0,Democrat,Bernie Sanders,395,0.386
9,Alabama,AL,Blount,1009.0,Democrat,Hillary Clinton,564,0.551
10,Alabama,AL,Bullock,1011.0,Democrat,Bernie Sanders,178,0.066
11,Alabama,AL,Bullock,1011.0,Democrat,Hillary Clinton,2451,0.913
12,Alabama,AL,Butler,1013.0,Democrat,Bernie Sanders,156,0.065
13,Alabama,AL,Butler,1013.0,Democrat,Hillary Clinton,2196,0.921
14,Alabama,AL,Calhoun,1015.0,Democrat,Bernie Sanders,1425,0.218
15,Alabama,AL,Calhoun,1015.0,Democrat,Hillary Clinton,5011,0.765
16,Alabama,AL,Chambers,1017.0,Democrat,Bernie Sanders,312,0.095
17,Alabama,AL,Chambers,1017.0,Democrat,Hillary Clinton,2899,0.886
18,Alabama,AL,Cherokee,1019.0,Democrat,Bernie Sanders,268,0.249
19,Alabama,AL,Cherokee,1019.0,Democrat,Hillary Clinton,712,0.661
20,Alabama,AL,Chilton,1021.0,Democrat,Bernie Sanders,289,0.246
21,Alabama,AL,Chilton,1021.0,Democrat,Hillary Clinton,860,0.731
22,Alabama,AL,Choctaw,1023.0,Democrat,Bernie Sanders,273,0.124
23,Alabama,AL,Choctaw,1023.0,Democrat,Hillary Clinton,1772,0.802
24,Alabama,AL,Clarke,1025.0,Democrat,Bernie Sanders,213,0.063
25,Alabama,AL,Clarke,1025.0,Democrat,Hillary Clinton,3148,0.930
26,Alabama,AL,Clay,1027.0,Democrat,Bernie Sanders,135,0.137
27,Alabama,AL,Clay,1027.0,Democrat,Hillary Clinton,807,0.818
28,Alabama,AL,Cleburne,1029.0,Democrat,Bernie Sanders,72,0.238
29,Alabama,AL,Cleburne,1029.0,Democrat,Hillary Clinton,221,0.732
...,...,...,...,...,...,...,...,...
439,Alabama,AL,Tallapoosa,1123.0,Republican,Ben Carson,1006,0.114
440,Alabama,AL,Tallapoosa,1123.0,Republican,Donald Trump,4658,0.528
441,Alabama,AL,Tallapoosa,1123.0,Republican,John Kasich,371,0.042
442,Alabama,AL,Tallapoosa,1123.0,Republican,Marco Rubio,1289,0.146
443,Alabama,AL,Tallapoosa,1123.0,Republican,Ted Cruz,1325,0.150
444,Alabama,AL,Tuscaloosa,1125.0,Republican,Ben Carson,3310,0.106
445,Alabama,AL,Tuscaloosa,1125.0,Republican,Donald Trump,11652,0.375
446,Alabama,AL,Tuscaloosa,1125.0,Republican,John Kasich,1381,0.044
447,Alabama,AL,Tuscaloosa,1125.0,Republican,Marco Rubio,6333,0.204
448,Alabama,AL,Tuscaloosa,1125.0,Republican,Ted Cruz,7789,0.250
449,Alabama,AL,Walker,1127.0,Republican,Ben Carson,1369,0.090
450,Alabama,AL,Walker,1127.0,Republican,Donald Trump,8394,0.551
451,Alabama,AL,Walker,1127.0,Republican,John Kasich,362,0.024
452,Alabama,AL,Walker,1127.0,Republican,Marco Rubio,1652,0.108
453,Alabama,AL,Walker,1127.0,Republican,Ted Cruz,3106,0.204
454,Alabama,AL,Washington,1129.0,Republican,Ben Carson,152,0.064
455,Alabama,AL,Washington,1129.0,Republican,Donald Trump,1269,0.537
456,Alabama,AL,Washington,1129.0,Republican,John Kasich,27,0.011
457,Alabama,AL,Washington,1129.0,Republican,Marco Rubio,362,0.153
458,Alabama,AL,Washington,1129.0,Republican,Ted Cruz,516,0.218
459,Alabama,AL,Wilcox,1131.0,Republican,Ben Carson,44,0.083
460,Alabama,AL,Wilcox,1131.0,Republican,Donald Trump,287,0.544
461,Alabama,AL,Wilcox,1131.0,Republican,John Kasich,12,0.023
462,Alabama,AL,Wilcox,1131.0,Republican,Marco Rubio,64,0.121
463,Alabama,AL,Wilcox,1131.0,Republican,Ted Cruz,114,0.216
464,Alabama,AL,Winston,1133.0,Republican,Ben Carson,539,0.090
465,Alabama,AL,Winston,1133.0,Republican,Donald Trump,3352,0.561
466,Alabama,AL,Winston,1133.0,Republican,John Kasich,163,0.027
467,Alabama,AL,Winston,1133.0,Republican,Marco Rubio,708,0.119
468,Alabama,AL,Winston,1133.0,Republican,Ted Cruz,1076,0.180

In [7]:
candidates = df_results['candidate'].unique()
candidates

array(['Bernie Sanders', 'Hillary Clinton', 'Ben Carson', 'Donald Trump',
       'John Kasich', 'Marco Rubio', 'Ted Cruz', ' Uncommitted',
       "Martin O'Malley", 'Carly Fiorina', 'Chris Christie', 'Jeb Bush',
       'Mike Huckabee', 'Rand Paul', 'Rick Santorum', ' No Preference'], dtype=object)

In [8]:
county_id = 'fips'
df_ = df_results[[county_id,'votes','candidate']]
df_pivot = df_.pivot_table(index=county_id, columns='candidate', values='votes').fillna(0.0).astype('int')
df_pivot.head()

candidate,No Preference,Uncommitted,Ben Carson,Bernie Sanders,Carly Fiorina,Chris Christie,Donald Trump,Hillary Clinton,Jeb Bush,John Kasich,Marco Rubio,Martin O'Malley,Mike Huckabee,Rand Paul,Rick Santorum,Ted Cruz
fips,,,,,,,,,,,,,,,,
1001.0,0,0,1764,544,0,0,5387,2387,0,421,1785,0,0,0,0,2482
1003.0,0,0,4221,2694,0,0,23618,5290,0,2987,9703,0,0,0,0,8571
1005.0,0,0,417,222,0,0,1710,2567,0,123,498,0,0,0,0,609
1007.0,0,0,393,246,0,0,1959,942,0,84,444,0,0,0,0,1011
1009.0,0,0,1523,395,0,0,7390,564,0,337,1843,0,0,0,0,3698

In [9]:
df_pivot['votes']=df_pivot.sum(axis = 1)
df_pivot[county_id] = df_pivot.index
for candidate in candidates:
    df_pivot[candidate + ' prop'] = df_pivot[candidate]/df_pivot['votes']
df_pivot.to_csv('county_candidate_votes.csv')
df_pivot.head()

candidate,No Preference,Uncommitted,Ben Carson,Bernie Sanders,Carly Fiorina,Chris Christie,Donald Trump,Hillary Clinton,Jeb Bush,John Kasich,Marco Rubio,Martin O'Malley,Mike Huckabee,Rand Paul,Rick Santorum,Ted Cruz,votes,fips
fips,,,,,,,,,,,,,,,,,,
1001.0,0,0,1764,544,0,0,5387,2387,0,421,1785,0,0,0,0,2482,14770,1001.0
1003.0,0,0,4221,2694,0,0,23618,5290,0,2987,9703,0,0,0,0,8571,57084,1003.0
1005.0,0,0,417,222,0,0,1710,2567,0,123,498,0,0,0,0,609,6146,1005.0
1007.0,0,0,393,246,0,0,1959,942,0,84,444,0,0,0,0,1011,5079,1007.0
1009.0,0,0,1523,395,0,0,7390,564,0,337,1843,0,0,0,0,3698,15750,1009.0

In [10]:
df_facts.head()

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
0,0,United States,NaN,318857056,308758105,3.3,308745538,6.2,23.1,14.5,...,8.3,28.8,5319456312,4174286516,3917663456,12990,613795732,1046363,3531905.43,87.4
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,1.2,28.1,112858843,52252752,57344851,12364,6426342,13369,50645.33,94.4
2,1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
3,1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
4,1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0

In [11]:
df = pd.merge(df_facts, df_pivot, how = 'left', left_on=county_id, right_on=county_id)
df.head()

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,Hillary Clinton,Jeb Bush,John Kasich,Marco Rubio,Martin O'Malley,Mike Huckabee,Rand Paul,Rick Santorum,Ted Cruz,votes
0,0,United States,NaN,318857056,308758105,3.3,308745538,6.2,23.1,14.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,...,2387.0,0.0,421.0,1785.0,0.0,0.0,0.0,0.0,2482.0,14770.0
3,1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,...,5290.0,0.0,2987.0,9703.0,0.0,0.0,0.0,0.0,8571.0,57084.0
4,1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,...,2567.0,0.0,123.0,498.0,0.0,0.0,0.0,0.0,609.0,6146.0

In [14]:
df_pivot.to_csv('county_candidate_votes_and_facts.csv')

In [13]:
from matplotlib import pyplot as plt
plt.plot(df.EDU635213,df.,'r.')
plt.show()

SyntaxError: invalid syntax (<ipython-input-13-1c9d503552ce>, line 2)